site_name: Competitive Programming Document

theme:
    name: material

markdown_extensions:
    - admonition

nav:
    - Home: index.md
    - Syntax:
        - String: syntax/string.md
        - Vector: syntax/vector.md
        - Set: syntax/set.md
        - Map: syntax/map.md
        - Pair: syntax/pair.md
    - Math:
        - Math: math/math.md
        - GCD: math/gcd.md
        - POW: math/pow.md
        - Prime: math/prime.md
        - ModInt: math/modint.md
    - graph:
        - Graph: graph/graph.md
        - DFS: graph/dfs.md
        - BFS: graph/bfs.md
        - Dijkstra: graph/dijkstra.md
        - TSP: graph/tsp.md
        - Union Find: graph/union_find.md
        - Segment Tree: graph/segment_tree.md
    - Util:
        - Utility: util/utility.md
        - Boost: util/boost.md
        - N 進数: util/n_ary.md
